language: r
r:
  - oldrel
  - release
  - devel
  
os: 
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
    
dist: xenial



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libsqlite3-dev
      - libgdal-dev
      - libnetcdf-dev
      - netcdf-bin
      - libudunits2-dev
      - libcurl4-openssl-dev
  homebrew:
    packages:
      - pkg-config
      - gdal
      - netcdf
      - sqlite
      - curl
      - libgit2
      - udunits
    update: true


r_check_args: "--no-manual --no-vignettes --as-cran"
r_build_args: "--no-build-vignettes"
warnings_are_errors: false      